use_frameworks!

platform :ios, '8.0'

target 'TSToolkit_Example' do
  pod 'TSToolkit', :path => '../'

  target 'TSToolkit_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
